<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <AssemblyName>hdr2sdr</AssemblyName>
    <RootNamespace>Hdr2Sdr.Helper</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../assets/icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../assets/icon.ico" LogicalName="hdr2sdr.icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Hdr2Sdr.Core/Hdr2Sdr.Core.csproj" />
    <ProjectReference Include="../Hdr2Sdr.Windows/Hdr2Sdr.Windows.csproj" />
  </ItemGroup>
</Project>
